"""Realistic sample data so a fresh HEAVEN install shows value immediately.

A brand-new install opens to an empty dashboard, which makes it hard to tell the
tool even works. ``heaven demo`` (CLI) and ``POST /api/demo/seed`` (web "Load
sample data" button) both call :func:`seed_demo` to drop a realistic example
engagement — a spread of critical→info findings with evidence — into the same
engagement store the dashboard reads, so every page (Dashboard, Findings,
Finding Detail, Kill Chain, Coverage, Reports) lights up instantly.

The data is clearly labelled as a sample (engagement "demo (sample data)",
targets under the reserved ``demo.heaven.local`` / TEST-NET ``10.10.10.0/24``
ranges) and is fully idempotent — finding IDs are content hashes, so re-seeding
updates in place instead of duplicating. Nothing here touches the network.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Optional

DEMO_ENGAGEMENT = "demo (sample data)"
DEMO_SCAN_ID = "demo-scan-0001"  # stable id → re-seeding dedups, never duplicates
WEB = "https://demo.heaven.local"   # RFC-reserved .local — never resolves/scanned
HOST = "10.10.10.10"                 # RFC5737 TEST-NET-style placeholder host


def _f(severity: str, vuln_type: str, title: str, *, target: str, risk: float,
       param: str = "", endpoint: str = "", cve: str = "", confidence: float = 0.9,
       description: str = "", impact: str = "", remediation: str = "",
       payload: str = "", method: str = "GET", cwe: str = "", owasp: str = "") -> dict:
    """Build one finding dict in the shape EngagementStore.upsert_finding wants."""
    bucket = "high" if confidence >= 0.8 else "medium" if confidence >= 0.5 else "low"
    return {
        "target": target, "vuln_type": vuln_type, "title": title,
        "severity": severity, "confidence": confidence, "confidence_bucket": bucket,
        "cve_id": cve, "risk_score": risk, "param": param, "endpoint": endpoint,
        "method": method,
        "evidence": {
            "parameter": param, "payload": payload, "method": method,
            "url": endpoint or target,
            "description": description, "impact": impact, "remediation": remediation,
            "cwe": cwe, "owasp": owasp,
            "note": "Sample finding generated by `heaven demo` — not from a real scan.",
        },
    }


# ── The sample findings: 3 critical · 3 high · 4 medium · 2 low ──────────────
_FINDINGS: list[dict] = [
    _f("critical", "sqli", "SQL injection (error-based) in 'id'",
       target=WEB, endpoint=f"{WEB}/vulnerabilities/sqli/", param="id", risk=9.8,
       confidence=0.98, cwe="CWE-89", owasp="A03:2021",
       payload="id=1' AND 1=CONVERT(int,@@version)--",
       description="The 'id' parameter is concatenated into a SQL query. A single "
                   "quote triggers a database error disclosing the query.",
       impact="Full read/write of the application database; likely auth bypass.",
       remediation="Use parameterised queries / prepared statements; never build "
                   "SQL by string concatenation."),
    _f("critical", "cmdi", "OS command injection in 'ip'",
       target=WEB, endpoint=f"{WEB}/vulnerabilities/exec/", param="ip", risk=9.8,
       confidence=0.97, cwe="CWE-78", owasp="A03:2021", method="POST",
       payload="ip=127.0.0.1;id",
       description="The 'ip' field is passed to a shell. Appending ';id' returns "
                   "the output of the injected command (uid=33(www-data)).",
       impact="Remote code execution as the web-server user.",
       remediation="Avoid shell calls with user input; use an allowlist and a "
                   "no-shell exec API (e.g. subprocess with a fixed arg list)."),
    _f("critical", "docker_socket_exposed", "Docker daemon socket exposed (2375/tcp)",
       target=f"{HOST}:2375", risk=9.8, confidence=0.95, cwe="CWE-284",
       description="The Docker Engine API is reachable unauthenticated on 2375/tcp. "
                   "Anyone who can reach it can start a privileged container.",
       impact="Trivial host takeover — mount the host FS or run --privileged.",
       remediation="Never expose the Docker socket over TCP; require mTLS, or bind "
                   "to the local UNIX socket only."),

    _f("high", "xss", "Reflected XSS in 'q'",
       target=WEB, endpoint=f"{WEB}/search", param="q", risk=7.4, confidence=0.9,
       cwe="CWE-79", owasp="A03:2021", payload="q=<script>alert(document.domain)</script>",
       description="The search term is reflected into the page unencoded.",
       impact="Session theft / account takeover via crafted links.",
       remediation="Context-aware output encoding; a strict Content-Security-Policy."),
    _f("high", "idor", "IDOR — other users' records via 'user_id'",
       target=WEB, endpoint=f"{WEB}/api/account", param="user_id", risk=8.1,
       confidence=0.88, cwe="CWE-639", owasp="A01:2021", method="GET",
       payload="user_id=1002",
       description="Changing user_id returns another user's account object; no "
                   "ownership check is performed.",
       impact="Horizontal privilege escalation; PII disclosure.",
       remediation="Enforce per-object authorization on every request."),
    _f("high", "default_credentials", "Default SSH credentials (admin/admin)",
       target=f"{HOST}:22", risk=8.0, confidence=0.85, cwe="CWE-1392",
       description="The SSH service accepts the vendor-default admin/admin login.",
       impact="Interactive shell access to the host.",
       remediation="Disable default accounts; enforce key-based auth + strong "
                   "passwords."),

    _f("medium", "open_redirect", "Open redirect in 'next'",
       target=WEB, endpoint=f"{WEB}/login", param="next", risk=5.4, confidence=0.8,
       cwe="CWE-601", owasp="A01:2021", payload="next=https://evil.example",
       description="The 'next' parameter is used as a redirect target without "
                   "validation.",
       impact="Phishing / OAuth token theft via trusted-domain redirects.",
       remediation="Allow only relative paths or an explicit host allowlist."),
    _f("medium", "security_misconfig", "Missing security headers",
       target=WEB, risk=5.0, confidence=0.9, cwe="CWE-693", owasp="A05:2021",
       description="Responses lack Content-Security-Policy, X-Content-Type-Options, "
                   "and Strict-Transport-Security.",
       impact="Increases the blast radius of XSS / MIME-sniffing / SSL-strip.",
       remediation="Add CSP, X-Content-Type-Options: nosniff, and HSTS."),
    _f("medium", "weak_tls", "Weak TLS configuration (TLS 1.0 enabled)",
       target=f"{WEB}:443", risk=5.3, confidence=0.86, cwe="CWE-327",
       description="The server negotiates TLS 1.0 and offers CBC cipher suites.",
       impact="Susceptible to downgrade / BEAST-class attacks.",
       remediation="Disable TLS < 1.2; prefer AEAD cipher suites."),
    _f("medium", "csrf", "Cross-site request forgery on profile update",
       target=WEB, endpoint=f"{WEB}/profile/update", risk=5.1, confidence=0.78,
       cwe="CWE-352", owasp="A01:2021", method="POST",
       description="The profile-update form has no anti-CSRF token.",
       impact="Attacker can change a victim's email/password via a crafted page.",
       remediation="Add per-session CSRF tokens; set SameSite=Lax/Strict cookies."),

    _f("low", "server_version_disclosure", "Server version disclosure",
       target=WEB, risk=3.1, confidence=0.9, cwe="CWE-200",
       description="The Server header reveals 'Apache/2.4.29 (Ubuntu)'.",
       impact="Aids attackers in matching known CVEs to the exact version.",
       remediation="Suppress version banners (ServerTokens Prod)."),
    _f("low", "info_disclosure", "Verbose error leaks a stack trace",
       target=WEB, endpoint=f"{WEB}/api/orders", risk=2.8, confidence=0.82,
       cwe="CWE-209", owasp="A05:2021",
       description="A malformed request returns a full framework stack trace.",
       impact="Discloses file paths, library versions and internal logic.",
       remediation="Return generic error pages; log details server-side only."),
]


def resolve_demo_store(name: Optional[str] = None):
    """Resolve the engagement store the web dashboard reads by default.

    Mirrors ``heaven.api.server._engagement_store_factory`` exactly so that data
    seeded from the CLI (`heaven demo`) and from the web ("Load sample data")
    land in the *same* SQLite file — i.e. ``<data_dir>/engagements/default.db``.
    """
    from heaven.config import get_config
    from heaven.engagement import EngagementStore

    data_dir = get_config().data_dir
    path = name or os.environ.get("HEAVEN_ENGAGEMENT") or "default"
    p = Path(path)
    if not p.suffix and not p.is_absolute() and "/" not in path and "\\" not in path:
        p = data_dir / "engagements" / f"{path}.db"
    return EngagementStore(p)


def seed_demo(store: Any) -> dict:
    """Idempotently seed ``store`` with the demo engagement + findings.

    Returns a summary: ``{engagement, scan_id, findings, by_severity, targets}``.
    Safe to call repeatedly — content-hashed IDs dedupe.
    """
    store.create_engagement(
        DEMO_ENGAGEMENT,
        client="ACME Corp (sample)",
        statement_of_work="Illustrative data generated by `heaven demo`. No real "
                          "systems were scanned.",
    )
    for target, kind, crit in [
        (WEB, "url", "high"),
        (f"{HOST}/32", "host", "crown_jewel"),
        ("10.10.10.0/24", "network", "medium"),
    ]:
        store.add_scope(target, kind=kind, criticality=crit, notes="sample scope")

    store.record_scan_start(DEMO_SCAN_ID, name="Demo web + network scan", mode="full")
    by_sev: dict[str, int] = {}
    for finding in _FINDINGS:
        store.upsert_finding(DEMO_SCAN_ID, finding)
        by_sev[finding["severity"]] = by_sev.get(finding["severity"], 0) + 1

    summary = {
        "findings": len(_FINDINGS),
        "by_severity": by_sev,
        "targets": 3,
        "duration_seconds": 47,
        "demo": True,
    }
    store.record_scan_complete(DEMO_SCAN_ID, summary)
    return {
        "engagement": DEMO_ENGAGEMENT,
        "scan_id": DEMO_SCAN_ID,
        "findings": len(_FINDINGS),
        "by_severity": by_sev,
        "targets": 3,
    }
