"""Realistic sample data so a fresh HEAVEN install shows value immediately.

A brand-new install opens to an empty dashboard, which makes it hard to tell the
tool even works. ``heaven demo`` (CLI) and ``POST /api/demo/seed`` (web "Load
sample data" button) both call :func:`seed_demo` to drop a realistic example
engagement — a spread of critical→info findings with evidence — into the same
engagement store the dashboard reads, so every page (Dashboard, Findings,
Finding Detail, Assets, Kill Chain, Coverage, Reports) lights up instantly. The
scan summary also carries a small sample host/service inventory so the Assets
view and the report's Host & Service Inventory — including the web app's resolved
IP address — populate exactly as they would after a real scan.

The data is clearly labelled as a sample (engagement "demo (sample data)",
targets under the reserved ``demo.heaven.local`` / TEST-NET ``10.10.10.0/24``
ranges) and is fully idempotent — finding IDs are content hashes, so re-seeding
updates in place instead of duplicating. Nothing here touches the network.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

DEMO_ENGAGEMENT = "demo (sample data)"
DEMO_SCAN_ID = "demo-scan-0001"  # stable id → re-seeding dedups, never duplicates
WEB_HOST = "demo.heaven.local"       # RFC-reserved .local — never resolves/scanned
WEB_IP = "10.10.10.20"               # address the web app "resolved to" in the lab
WEB = f"https://{WEB_HOST}"          # web-app target used by the sample findings
HOST = "10.10.10.10"                 # RFC5737 TEST-NET-style placeholder host


def _f(severity: str, vuln_type: str, title: str, *, target: str, risk: float,
       param: str = "", endpoint: str = "", cve: str = "", confidence: float = 0.9,
       description: str = "", impact: str = "", remediation: str = "",
       payload: str = "", method: str = "GET", cwe: str = "", owasp: str = "") -> dict:
    """Build one finding dict in the shape EngagementStore.upsert_finding wants."""
    bucket = "high" if confidence >= 0.8 else "medium" if confidence >= 0.5 else "low"
    return {
        "target": target, "vuln_type": vuln_type, "title": title,
        "severity": severity, "confidence": confidence, "confidence_bucket": bucket,
        "cve_id": cve, "risk_score": risk, "param": param, "endpoint": endpoint,
        "method": method,
        "evidence": {
            "parameter": param, "payload": payload, "method": method,
            "url": endpoint or target,
            "description": description, "impact": impact, "remediation": remediation,
            "cwe": cwe, "owasp": owasp,
            "note": "Sample finding generated by `heaven demo` — not from a real scan.",
        },
    }


# ── The sample findings: 3 critical · 3 high · 4 medium · 2 low ──────────────
_FINDINGS: list[dict] = [
    _f("critical", "sqli", "SQL injection (error-based) in 'id'",
       target=WEB, endpoint=f"{WEB}/vulnerabilities/sqli/", param="id", risk=96.0,
       confidence=0.98, cwe="CWE-89", owasp="A05:2025",
       payload="id=1' AND 1=CONVERT(int,@@version)--",
       description="The 'id' parameter is concatenated into a SQL query. A single "
                   "quote triggers a database error disclosing the query.",
       impact="Full read/write of the application database; likely auth bypass.",
       remediation="Use parameterised queries / prepared statements; never build "
                   "SQL by string concatenation."),
    _f("critical", "cmdi", "OS command injection in 'ip'",
       target=WEB, endpoint=f"{WEB}/vulnerabilities/exec/", param="ip", risk=95.0,
       confidence=0.97, cwe="CWE-78", owasp="A05:2025", method="POST",
       payload="ip=127.0.0.1;id",
       description="The 'ip' field is passed to a shell. Appending ';id' returns "
                   "the output of the injected command (uid=33(www-data)).",
       impact="Remote code execution as the web-server user.",
       remediation="Avoid shell calls with user input; use an allowlist and a "
                   "no-shell exec API (e.g. subprocess with a fixed arg list)."),
    _f("critical", "docker_socket_exposed", "Docker daemon socket exposed (2375/tcp)",
       target=f"{HOST}:2375", risk=94.0, confidence=0.95, cwe="CWE-284",
       description="The Docker Engine API is reachable unauthenticated on 2375/tcp. "
                   "Anyone who can reach it can start a privileged container.",
       impact="Trivial host takeover — mount the host FS or run --privileged.",
       remediation="Never expose the Docker socket over TCP; require mTLS, or bind "
                   "to the local UNIX socket only."),

    _f("high", "xss", "Reflected XSS in 'q'",
       target=WEB, endpoint=f"{WEB}/search", param="q", risk=78.0, confidence=0.9,
       cwe="CWE-79", owasp="A05:2025", payload="q=<script>alert(document.domain)</script>",
       description="The search term is reflected into the page unencoded.",
       impact="Session theft / account takeover via crafted links.",
       remediation="Context-aware output encoding; a strict Content-Security-Policy."),
    _f("high", "idor", "IDOR — other users' records via 'user_id'",
       target=WEB, endpoint=f"{WEB}/api/account", param="user_id", risk=82.0,
       confidence=0.88, cwe="CWE-639", owasp="A01:2025", method="GET",
       payload="user_id=1002",
       description="Changing user_id returns another user's account object; no "
                   "ownership check is performed.",
       impact="Horizontal privilege escalation; PII disclosure.",
       remediation="Enforce per-object authorization on every request."),
    _f("high", "default_credentials", "Default SSH credentials (admin/admin)",
       target=f"{HOST}:22", risk=80.0, confidence=0.85, cwe="CWE-1392",
       description="The SSH service accepts the vendor-default admin/admin login.",
       impact="Interactive shell access to the host.",
       remediation="Disable default accounts; enforce key-based auth + strong "
                   "passwords."),

    _f("medium", "open_redirect", "Open redirect in 'next'",
       target=WEB, endpoint=f"{WEB}/login", param="next", risk=56.0, confidence=0.8,
       cwe="CWE-601", owasp="A06:2025", payload="next=https://evil.example",
       description="The 'next' parameter is used as a redirect target without "
                   "validation.",
       impact="Phishing / OAuth token theft via trusted-domain redirects.",
       remediation="Allow only relative paths or an explicit host allowlist."),
    _f("medium", "security_misconfig", "Missing security headers",
       target=WEB, risk=52.0, confidence=0.9, cwe="CWE-693", owasp="A02:2025",
       description="Responses lack Content-Security-Policy, X-Content-Type-Options, "
                   "and Strict-Transport-Security.",
       impact="Increases the blast radius of XSS / MIME-sniffing / SSL-strip.",
       remediation="Add CSP, X-Content-Type-Options: nosniff, and HSTS."),
    _f("medium", "weak_tls", "Weak TLS configuration (TLS 1.0 enabled)",
       target=f"{WEB}:443", risk=55.0, confidence=0.86, cwe="CWE-327",
       description="The server negotiates TLS 1.0 and offers CBC cipher suites.",
       impact="Susceptible to downgrade / BEAST-class attacks.",
       remediation="Disable TLS < 1.2; prefer AEAD cipher suites."),
    _f("medium", "csrf", "Cross-site request forgery on profile update",
       target=WEB, endpoint=f"{WEB}/profile/update", risk=53.0, confidence=0.78,
       cwe="CWE-352", owasp="A01:2025", method="POST",
       description="The profile-update form has no anti-CSRF token.",
       impact="Attacker can change a victim's email/password via a crafted page.",
       remediation="Add per-session CSRF tokens; set SameSite=Lax/Strict cookies."),

    _f("low", "server_version_disclosure", "Server version disclosure",
       target=WEB, risk=32.0, confidence=0.9, cwe="CWE-200",
       description="The Server header reveals 'Apache/2.4.29 (Ubuntu)'.",
       impact="Aids attackers in matching known CVEs to the exact version.",
       remediation="Suppress version banners (ServerTokens Prod)."),
    _f("low", "info_disclosure", "Verbose error leaks a stack trace",
       target=WEB, endpoint=f"{WEB}/api/orders", risk=28.0, confidence=0.82,
       cwe="CWE-209", owasp="A10:2025",
       description="A malformed request returns a full framework stack trace.",
       impact="Discloses file paths, library versions and internal logic.",
       remediation="Return generic error pages; log details server-side only."),
]


# ── The sample host & service inventory ──────────────────────────────────────
# A realistic little lab topology inside the demo's 10.10.10.0/24 scope, so the
# Assets page and the report's Host & Service Inventory light up the same way a
# real network scan would — and, crucially, so the web-app target shows both its
# hostname AND the address it resolved to (the IP column). Every value here is
# clearly part of the labelled sample engagement; nothing was scanned.
_ASSETS: list[dict] = [
    {
        # Web application — a HOSTNAME target that resolved to a distinct IP, so
        # the inventory shows "demo.heaven.local" with an "IP: 10.10.10.20" line.
        "host": WEB_HOST, "ip": WEB_IP, "is_alive": True,
        "os": "Linux 4.15 - 5.8 (Ubuntu)", "os_source": "nmap", "os_accuracy": 96,
        "device_type": "web server", "device_type_source": "service-heuristic",
        "open_ports": [
            {"port": 22, "protocol": "tcp", "service": "ssh", "product": "OpenSSH",
             "version": "7.6p1 Ubuntu 4ubuntu0.7",
             "cpe": "cpe:/a:openbsd:openssh:7.6p1",
             "banner": "SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.7"},
            {"port": 80, "protocol": "tcp", "service": "http", "product": "Apache httpd",
             "version": "2.4.29 ((Ubuntu))",
             "cpe": "cpe:/a:apache:http_server:2.4.29", "banner": "Apache/2.4.29 (Ubuntu)"},
            {"port": 443, "protocol": "tcp", "service": "ssl/http", "product": "Apache httpd",
             "version": "2.4.29 ((Ubuntu))",
             "cpe": "cpe:/a:apache:http_server:2.4.29", "banner": "Apache/2.4.29 (Ubuntu)"},
            {"port": 3306, "protocol": "tcp", "service": "mysql", "product": "MySQL",
             "version": "5.7.33", "cpe": "cpe:/a:mysql:mysql:5.7.33",
             "banner": "5.7.33-0ubuntu0.18.04.1"},
        ],
        "web_components": [
            {"service": "apache", "version": "2.4.29"},
            {"service": "php", "version": "7.2.24"},
            {"service": "openssl", "version": "1.1.1"},
        ],
    },
    {
        # Crown-jewel host — the exposed Docker/SSH box the sample findings hit.
        "host": HOST, "ip": HOST, "is_alive": True,
        "os": "Linux 3.13 - 4.9 (Debian)", "os_source": "nmap", "os_accuracy": 92,
        "mac_address": "00:0c:29:4b:1a:7e", "mac_vendor": "VMware, Inc.",
        "device_type": "server", "device_type_source": "service-heuristic",
        "open_ports": [
            {"port": 22, "protocol": "tcp", "service": "ssh", "product": "OpenSSH",
             "version": "6.6.1p1 Debian 4~bpo70+1",
             "cpe": "cpe:/a:openbsd:openssh:6.6.1p1",
             "banner": "SSH-2.0-OpenSSH_6.6.1p1 Debian-4~bpo70+1"},
            {"port": 2375, "protocol": "tcp", "service": "docker", "product": "Docker",
             "version": "18.06.1-ce", "cpe": "cpe:/a:docker:docker:18.06.1",
             "banner": "HTTP/1.1 200 OK — Docker Engine API"},
        ],
    },
    {
        # Edge gateway — demonstrates MAC + device-name/type identity columns.
        "host": "10.10.10.1", "ip": "10.10.10.1", "is_alive": True,
        "mac_address": "f0:9f:c2:11:22:33", "mac_vendor": "Ubiquiti Inc.",
        "device_name": "gw-edge-01", "device_name_source": "ptr",
        "device_type": "router", "device_type_source": "mac-vendor",
        "open_ports": [
            {"port": 53, "protocol": "tcp", "service": "domain", "product": "dnsmasq",
             "version": "2.79", "cpe": "cpe:/a:thekelleys:dnsmasq:2.79"},
            {"port": 80, "protocol": "tcp", "service": "http", "product": "lighttpd",
             "version": "1.4.45", "banner": "lighttpd/1.4.45"},
            {"port": 443, "protocol": "tcp", "service": "ssl/http", "product": "lighttpd",
             "version": "1.4.45"},
        ],
    },
]


def resolve_demo_store(name: Optional[str] = None):
    """Resolve the engagement store that holds the sample data.

    Sample data lives in its OWN engagement DB (``engagements/demo.db``) so it
    never contaminates a real engagement. Both the CLI (`heaven demo`) and the
    web ("Load sample data" / "Run demo scan") resolve to the same file, and the
    caller switches the active pointer to it so the dashboard shows the sample.
    An explicit *name* (e.g. `heaven demo --engagement foo`) overrides this.
    """
    from heaven.config import get_config
    from heaven.engagement import DEMO_DB_NAME, EngagementStore

    data_dir = get_config().data_dir
    path = name or DEMO_DB_NAME
    p = Path(path)
    if not p.suffix and not p.is_absolute() and "/" not in path and "\\" not in path:
        p = data_dir / "engagements" / f"{path}.db"
    return EngagementStore(p)


def insert_findings(store: Any, scan_id: str) -> dict:
    """Create the demo engagement/scope and upsert the sample findings under
    ``scan_id`` (without touching scan start/complete). Returns a summary dict
    including a ``summary`` sub-dict suitable for ``record_scan_complete``.

    Factored out so both the instant "Load sample data" path (:func:`seed_demo`)
    and the animated "Run demo scan" path (the API's background task) share the
    exact same findings.
    """
    store.create_engagement(
        DEMO_ENGAGEMENT,
        client="ACME Corp (sample)",
        statement_of_work="Illustrative data generated by `heaven demo`. No real "
                          "systems were scanned.",
    )
    for target, kind, crit in [
        (WEB, "url", "high"),
        (f"{HOST}/32", "host", "crown_jewel"),
        ("10.10.10.0/24", "network", "medium"),
    ]:
        store.add_scope(target, kind=kind, criticality=crit, notes="sample scope")

    by_sev: dict[str, int] = {}
    for finding in _FINDINGS:
        store.upsert_finding(scan_id, finding)
        by_sev[finding["severity"]] = by_sev.get(finding["severity"], 0) + 1

    summary = {
        "findings": len(_FINDINGS), "by_severity": by_sev,
        "targets": 3, "duration_seconds": 47, "demo": True,
        # Host & service inventory so the Assets page + report inventory populate
        # (and the web app shows its hostname alongside the resolved IP).
        "assets": [dict(a) for a in _ASSETS],
    }
    return {
        "engagement": DEMO_ENGAGEMENT, "scan_id": scan_id,
        "findings": len(_FINDINGS), "by_severity": by_sev, "targets": 3,
        "summary": summary,
    }


def seed_demo(store: Any, scan_id: str = DEMO_SCAN_ID) -> dict:
    """Idempotently seed ``store`` with the demo engagement + a completed scan.

    Returns ``{engagement, scan_id, findings, by_severity, targets}``. Safe to
    call repeatedly — content-hashed IDs dedupe.
    """
    store.record_scan_start(scan_id, name="Demo web + network scan", mode="full")
    res = insert_findings(store, scan_id)
    store.record_scan_complete(scan_id, res["summary"])
    return {k: res[k] for k in ("engagement", "scan_id", "findings", "by_severity", "targets")}
