"""Tests for the email security scanner.

No live DNS or mail server is required: DNS is mocked with crafted records and
the SMTP relay / user-enumeration path is exercised against a tiny local SMTP
server bound to an ephemeral port. DKIM key-strength is verified with *real*
RSA keys generated by ``cryptography`` so the DER-decode path is genuinely
tested, not stubbed.
"""

from __future__ import annotations

import asyncio
import base64

import dns.resolver
import pytest
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    PublicFormat,
)

from heaven.recon.email_scanner import EmailSecurityScanner, scan_email_domains


# ── DNS mock ────────────────────────────────────────────────────────────────
class _TXT:
    def __init__(self, text: str):
        self._t = text

    def __str__(self) -> str:
        return self._t


class _MX:
    def __init__(self, preference: int, exchange: str):
        self.preference = preference
        self.exchange = exchange


def _install_dns(monkeypatch, records: dict):
    """Patch dns.resolver.resolve with a static (qname, rdtype) -> value map.

    A value that is an Exception instance is raised; a missing key raises
    NoAnswer (the "record does not exist" case the scanner treats as absent).
    """
    def _resolve(qname, rdtype, *a, **k):
        key = (str(qname).rstrip("."), rdtype)
        val = records.get(key)
        if val is None:
            raise dns.resolver.NoAnswer
        if isinstance(val, Exception):
            raise val
        return val
    monkeypatch.setattr(dns.resolver, "resolve", _resolve)


def _dkim_txt(bits: int) -> str:
    key = rsa.generate_private_key(public_exponent=65537, key_size=bits)
    der = key.public_key().public_bytes(
        Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    b64 = base64.b64encode(der).decode()
    return f"v=DKIM1; k=rsa; p={b64}"


# A real 512-bit RSA public key (SPKI DER, base64). cryptography refuses to
# *generate* keys below 1024 bits, but loading an existing small key (as we do
# when parsing a published DKIM record) is allowed — this is exactly that case.
_RSA_512_SPKI_B64 = (
    "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALxA+9XOsyrHUdPx4fWoth2s5NATzh15Fddk6L/"
    "liQNKCXy9Y86NYW7VA9hYFdizXXmv6aqILO0HB9I01ZnTzFcCAwEAAQ=="
)


def _dkim_txt_512() -> str:
    return f"v=DKIM1; k=rsa; p={_RSA_512_SPKI_B64}"


def _types(findings) -> set:
    return {f.vuln_type for f in findings}


# ── DKIM key decode (real crypto) ───────────────────────────────────────────
def test_dkim_key_bits_real_2048():
    txt = _dkim_txt(2048)
    p = txt.split("p=")[1]
    bits, algo = EmailSecurityScanner._dkim_key_bits(p)
    assert bits == 2048
    assert algo == "rsa"


def test_dkim_key_bits_garbage_returns_none():
    bits, algo = EmailSecurityScanner._dkim_key_bits("not-a-real-key")
    assert bits is None
    assert algo == ""


def test_dkim_key_bits_empty_is_revoked_selector():
    bits, algo = EmailSecurityScanner._dkim_key_bits("")
    assert bits is None


@pytest.mark.asyncio
async def test_dkim_weak_512_bit_flags_high(monkeypatch):
    _install_dns(monkeypatch, {
        ("google._domainkey.example.com", "TXT"): [_TXT(_dkim_txt_512())],
    })
    s = EmailSecurityScanner()
    await s.check_dkim("example.com")
    weak = [f for f in s._findings if f.vuln_type == "dkim_weak_key"]
    assert weak and weak[0].severity == "high"
    assert weak[0].evidence.get("key_bits") == 512


@pytest.mark.asyncio
async def test_dkim_legacy_1024_bit_flags_low(monkeypatch):
    _install_dns(monkeypatch, {
        ("google._domainkey.example.com", "TXT"): [_TXT(_dkim_txt(1024))],
    })
    s = EmailSecurityScanner()
    await s.check_dkim("example.com")
    legacy = [f for f in s._findings if f.vuln_type == "dkim_weak_key"]
    assert legacy and legacy[0].severity == "low"


@pytest.mark.asyncio
async def test_dkim_2048_is_not_flagged_weak(monkeypatch):
    _install_dns(monkeypatch, {
        ("selector1._domainkey.example.com", "TXT"): [_TXT(_dkim_txt(2048))],
    })
    s = EmailSecurityScanner()
    await s.check_dkim("example.com")
    assert "dkim_weak_key" not in _types(s._findings)
    assert "dkim_found" in _types(s._findings)


# ── SPF ─────────────────────────────────────────────────────────────────────
@pytest.mark.asyncio
async def test_spf_plus_all_is_critical(monkeypatch):
    _install_dns(monkeypatch, {
        ("example.com", "TXT"): [_TXT("v=spf1 +all")],
    })
    s = EmailSecurityScanner()
    await s.check_spf("example.com")
    spf = [f for f in s._findings if f.vuln_type == "spf_analysis"]
    assert spf and spf[0].severity == "critical"


@pytest.mark.asyncio
async def test_spf_missing_when_no_spf_txt(monkeypatch):
    _install_dns(monkeypatch, {
        ("example.com", "TXT"): [_TXT("some-unrelated-verification=abc")],
    })
    s = EmailSecurityScanner()
    await s.check_spf("example.com")
    assert "spf_missing" in _types(s._findings)


# ── DMARC subdomain policy ──────────────────────────────────────────────────
@pytest.mark.asyncio
async def test_dmarc_subdomain_policy_weaker_than_domain(monkeypatch):
    _install_dns(monkeypatch, {
        ("_dmarc.example.com", "TXT"):
            [_TXT("v=DMARC1; p=reject; sp=none; rua=mailto:d@example.com")],
    })
    s = EmailSecurityScanner()
    await s.check_dmarc("example.com")
    assert "dmarc_subdomain_policy_weak" in _types(s._findings)
    weak = [f for f in s._findings
            if f.vuln_type == "dmarc_subdomain_policy_weak"][0]
    assert weak.severity == "medium"
    assert weak.evidence["subdomain_policy"] == "none"


@pytest.mark.asyncio
async def test_dmarc_reject_no_subdomain_finding(monkeypatch):
    _install_dns(monkeypatch, {
        ("_dmarc.example.com", "TXT"):
            [_TXT("v=DMARC1; p=reject; rua=mailto:d@example.com")],
    })
    s = EmailSecurityScanner()
    await s.check_dmarc("example.com")
    assert "dmarc_subdomain_policy_weak" not in _types(s._findings)
    dmarc = [f for f in s._findings if f.vuln_type == "dmarc_analysis"][0]
    assert dmarc.evidence["adkim"] == "r"  # relaxed default recorded


# ── BIMI ────────────────────────────────────────────────────────────────────
@pytest.mark.asyncio
async def test_bimi_configured_is_info(monkeypatch):
    _install_dns(monkeypatch, {
        ("default._bimi.example.com", "TXT"):
            [_TXT("v=BIMI1; l=https://example.com/logo.svg")],
    })
    s = EmailSecurityScanner()
    await s.check_bimi("example.com")
    assert "bimi_configured" in _types(s._findings)


@pytest.mark.asyncio
async def test_bimi_missing_only_when_dmarc_enforced(monkeypatch):
    _install_dns(monkeypatch, {})  # no BIMI record
    # Enforced DMARC present -> missing BIMI is reported (low).
    s = EmailSecurityScanner()
    s._findings.append(_dmarc_finding("reject"))
    await s.check_bimi("example.com")
    assert "bimi_missing" in _types(s._findings)


@pytest.mark.asyncio
async def test_bimi_not_reported_without_enforcement(monkeypatch):
    _install_dns(monkeypatch, {})  # no BIMI record
    s = EmailSecurityScanner()
    s._findings.append(_dmarc_finding("none"))
    await s.check_bimi("example.com")
    assert "bimi_missing" not in _types(s._findings)


def _dmarc_finding(policy: str):
    from heaven.recon.email_scanner import EmailFinding
    return EmailFinding(
        target="example.com", vuln_type="dmarc_analysis", severity="info",
        title="", description="", evidence={"policy": policy})


# ── SMTP user enumeration + relay (local server) ────────────────────────────
async def _start_fake_smtp(*, starttls=True, vrfy_enum=True, open_relay=False):
    async def handle(reader, writer):
        async def send(s: str):
            writer.write(s.encode())
            await writer.drain()
        await send("220 fake ESMTP\r\n")
        while True:
            line = await reader.readline()
            if not line:
                break
            cmd = line.decode(errors="ignore").strip()
            u = cmd.upper()
            if u.startswith(("EHLO", "HELO")):
                await send("250-fake.example\r\n"
                           + ("250 STARTTLS\r\n" if starttls else "250 OK\r\n"))
            elif u.startswith("VRFY"):
                arg = cmd[4:].strip().lower()
                if vrfy_enum:
                    await send("250 <postmaster@fake>\r\n"
                               if arg.startswith("postmaster")
                               else "550 no such user\r\n")
                else:
                    await send("252 cannot VRFY\r\n")
            elif u.startswith("MAIL FROM"):
                await send("250 OK\r\n")
            elif u.startswith("RCPT TO"):
                await send("250 OK\r\n" if open_relay else "550 relay denied\r\n")
            elif u.startswith("RSET"):
                await send("250 OK\r\n")
            elif u.startswith("QUIT"):
                await send("221 bye\r\n")
                break
            else:
                await send("250 OK\r\n")
        writer.close()
    server = await asyncio.start_server(handle, "127.0.0.1", 0)
    port = server.sockets[0].getsockname()[1]
    return server, port


def _mx_finding():
    from heaven.recon.email_scanner import EmailFinding
    return EmailFinding(
        target="example.com", vuln_type="mx_enumeration", severity="info",
        title="", description="",
        evidence={"mx_records": [{"priority": 10, "server": "127.0.0.1"}]})


@pytest.mark.asyncio
async def test_smtp_user_enumeration_detected():
    server, port = await _start_fake_smtp(vrfy_enum=True)
    try:
        s = EmailSecurityScanner(timeout=3.0)
        s._smtp_port = port
        s._findings.append(_mx_finding())
        await s.check_smtp_relay("example.com")
    finally:
        server.close()
        await server.wait_closed()
    assert "smtp_user_enumeration" in _types(s._findings)


@pytest.mark.asyncio
async def test_smtp_no_user_enumeration_when_uniform():
    server, port = await _start_fake_smtp(vrfy_enum=False)
    try:
        s = EmailSecurityScanner(timeout=3.0)
        s._smtp_port = port
        s._findings.append(_mx_finding())
        await s.check_smtp_relay("example.com")
    finally:
        server.close()
        await server.wait_closed()
    assert "smtp_user_enumeration" not in _types(s._findings)


@pytest.mark.asyncio
async def test_smtp_open_relay_and_no_starttls():
    server, port = await _start_fake_smtp(starttls=False, open_relay=True)
    try:
        s = EmailSecurityScanner(timeout=3.0)
        s._smtp_port = port
        s._findings.append(_mx_finding())
        await s.check_smtp_relay("example.com")
    finally:
        server.close()
        await server.wait_closed()
    got = _types(s._findings)
    assert "smtp_open_relay" in got
    assert "smtp_no_starttls" in got


# ── direct raw-endpoint probe (no MX lookup) ────────────────────────────────
# The open-relay lab and the orchestrator's bare-SMTP injection reach the probe
# through scan_smtp_server / scan_smtp_endpoint, which run against a host:port
# with no MX record at all. These exercise that path deterministically.
@pytest.mark.asyncio
async def test_scan_smtp_server_direct_detects_open_relay():
    server, port = await _start_fake_smtp(starttls=False, open_relay=True)
    try:
        s = EmailSecurityScanner(timeout=3.0)
        findings = await s.scan_smtp_server("127.0.0.1", port)
    finally:
        server.close()
        await server.wait_closed()
    got = _types(findings)
    assert "smtp_open_relay" in got  # detected with NO mx_enumeration finding
    assert "smtp_no_starttls" in got


@pytest.mark.asyncio
async def test_scan_smtp_endpoint_shapes_result():
    from heaven.recon.email_scanner import scan_smtp_endpoint
    server, port = await _start_fake_smtp(starttls=True, open_relay=False)
    try:
        res = await scan_smtp_endpoint("127.0.0.1", port)
    finally:
        server.close()
        await server.wait_closed()
    # A closed (non-relaying) server with STARTTLS yields no relay/starttls finding.
    types = {f["vuln_type"] for f in res["findings"]}
    assert res["total"] == len(res["findings"])
    assert "smtp_open_relay" not in types
    assert "smtp_no_starttls" not in types


# ── entry point ─────────────────────────────────────────────────────────────
@pytest.mark.asyncio
async def test_scan_email_domains_skips_when_empty():
    result = await scan_email_domains([])
    assert result.get("skipped") is True
