"""
HEAVEN — Adaptive Scanning Intelligence
Real-time scan strategy adaptation based on target responses.
Like a human pentester: observe → hypothesize → test → adapt.

Features:
- WAF/IDS fingerprinting and automatic bypass selection
- Service-specific deep-dive when interesting targets found
- Automatic escalation from recon → exploitation when vulns found
- Smart port prediction based on discovered services
- Rate adaptation based on target responsiveness
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Optional

try:
    import aiohttp
except ImportError:
    aiohttp = None  # type: ignore[assignment]

from heaven.recon.evasion_engine import EvasionEngine, EvasionProfile, StealthLevel
from heaven.utils.logger import get_logger

logger = get_logger("adaptive")


# ── WAF/IDS Fingerprinting ──

WAF_SIGNATURES: dict[str, dict[str, list[str] | list[int]]] = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "server: cloudflare"],
        "body": ["attention required! | cloudflare", "ray id:", "cloudflare"],
        "status_on_block": [403, 503],
        "bypass_techniques": ["unicode_normalize", "chunked_encoding", "case_alternation",
                              "path_segment_bypass", "header_pollution"],
    },
    "aws_waf": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body": ["request blocked", "aws waf"],
        "status_on_block": [403],
        "bypass_techniques": ["unicode_normalize", "double_url_encode", "json_content_type"],
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-grn"],
        "body": ["access denied", "akamai"],
        "status_on_block": [403],
        "bypass_techniques": ["parameter_pollution", "multipart_encoding", "chunked_transfer"],
    },
    "imperva": {
        "headers": ["x-iinfo", "x-cdn"],
        "body": ["incapsula incident id", "powered by incapsula"],
        "status_on_block": [403],
        "bypass_techniques": ["unicode_normalize", "comment_injection", "whitespace_manipulation"],
    },
    "modsecurity": {
        "headers": [],
        "body": ["mod_security", "modsecurity", "not acceptable", "rule id"],
        "status_on_block": [403, 406],
        "bypass_techniques": ["case_alternation", "comment_injection", "null_byte",
                              "double_url_encode", "unicode_normalize"],
    },
    "f5_bigip": {
        "headers": ["x-wa-info", "server: bigip"],
        "body": ["the requested url was rejected", "support id"],
        "status_on_block": [403],
        "bypass_techniques": ["chunked_transfer", "content_type_mismatch", "parameter_pollution"],
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache", "server: sucuri"],
        "body": ["sucuri", "access denied - sucuri"],
        "status_on_block": [403],
        "bypass_techniques": ["double_url_encode", "unicode_normalize"],
    },
    "wordfence": {
        "headers": [],
        "body": ["wordfence", "generated by wordfence", "a potentially unsafe operation"],
        "status_on_block": [403, 503],
        "bypass_techniques": ["unicode_normalize", "case_alternation", "param_name_mutation"],
    },
}


@dataclass
class WAFFingerprint:
    """Identified WAF/IDS protecting a target."""
    name: str
    confidence: float
    evidence: list[str] = field(default_factory=list)
    bypass_techniques: list[str] = field(default_factory=list)
    blocked_payloads: list[str] = field(default_factory=list)


@dataclass
class TargetProfile:
    """Accumulated intelligence about a target."""
    host: str
    waf: Optional[WAFFingerprint] = None
    technologies: list[str] = field(default_factory=list)
    framework: str = ""
    language: str = ""
    server: str = ""
    os_hint: str = ""
    avg_response_ms: float = 0.0
    error_rate: float = 0.0
    rate_limit_detected: bool = False
    rate_limit_threshold: int = 0
    interesting_headers: dict[str, str] = field(default_factory=dict)
    discovered_endpoints: list[str] = field(default_factory=list)
    input_vectors: list[dict] = field(default_factory=list)
    auth_type: str = ""              # basic, bearer, cookie, oauth, none
    api_style: str = ""              # rest, graphql, soap, grpc
    recommended_attacks: list[str] = field(default_factory=list)


class AdaptiveIntelligence:
    """
    Real-time scan intelligence that adapts strategy based on target behaviour.
    Thinks like a senior pentester: observe, hypothesize, test, adapt.
    """

    def __init__(self):
        self.profiles: dict[str, TargetProfile] = {}
        self.response_history: dict[str, list[dict]] = defaultdict(list)
        self._blocked_count: dict[str, int] = defaultdict(int)
        self._request_count: dict[str, int] = defaultdict(int)

    async def fingerprint_waf(self, session: aiohttp.ClientSession, url: str) -> Optional[WAFFingerprint]:
        """Identify WAF/IDS by sending probe requests and analyzing responses."""
        # Step 1: Benign request baseline
        try:
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                baseline_headers = dict(resp.headers)
                baseline_body = await resp.text()
        except Exception:
            return None

        # Check headers against known WAF signatures
        best_match = None
        best_confidence = 0.0

        headers_lower = {k.lower(): v.lower() for k, v in baseline_headers.items()}
        body_lower = baseline_body.lower()

        for waf_name, sigs in WAF_SIGNATURES.items():
            confidence = 0.0
            evidence = []
            header_sigs = [str(x) for x in sigs.get("headers", [])]
            body_sigs = [str(x) for x in sigs.get("body", [])]
            bypass_techniques = [str(x) for x in sigs.get("bypass_techniques", [])]

            for h in header_sigs:
                if ":" in h:
                    key, val = h.split(":", 1)
                    if key.strip() in headers_lower and val.strip() in headers_lower.get(key.strip(), ""):
                        confidence += 0.3
                        evidence.append(f"Header match: {h}")
                elif h in headers_lower:
                    confidence += 0.25
                    evidence.append(f"Header present: {h}")

            for pattern in body_sigs:
                if pattern in body_lower:
                    confidence += 0.2
                    evidence.append(f"Body pattern: {pattern}")

            if confidence > best_confidence:
                best_confidence = confidence
                best_match = WAFFingerprint(
                    name=waf_name, confidence=min(confidence, 1.0),
                    evidence=evidence, bypass_techniques=bypass_techniques,
                )

        # Step 2: Send a known-malicious probe to trigger WAF block
        malicious_probes = [
            "?id=1' OR 1=1--",
            "?q=<script>alert(1)</script>",
            "?file=../../../../etc/passwd",
        ]

        for probe in malicious_probes:
            try:
                probe_url = url.rstrip("/") + probe
                async with session.get(probe_url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                    probe_status = resp.status
                    (await resp.text()).lower()

                    if probe_status in (403, 406, 429, 503):
                        if best_match:
                            best_match.confidence = min(best_match.confidence + 0.3, 1.0)
                            best_match.blocked_payloads.append(probe)
                        else:
                            # Unknown WAF
                            best_match = WAFFingerprint(
                                name="unknown_waf", confidence=0.6,
                                evidence=[f"Blocked probe with {probe_status}"],
                                blocked_payloads=[probe],
                                bypass_techniques=["unicode_normalize", "double_url_encode",
                                                   "case_alternation", "comment_injection"],
                            )
            except Exception:
                pass

        if best_match and best_match.confidence >= 0.3:
            logger.info(f"🛡️ WAF detected: {best_match.name} (confidence={best_match.confidence:.0%}) — "
                        f"bypass techniques: {', '.join(best_match.bypass_techniques[:3])}")
            return best_match

        return None

    async def profile_target(self, session: aiohttp.ClientSession, url: str,
                             stealth_level: str = "normal") -> TargetProfile:
        """Build a comprehensive intelligence profile of a target."""
        profile = TargetProfile(host=url)

        stealth_map = {
            "aggressive": StealthLevel.AGGRESSIVE,
            "normal": StealthLevel.NORMAL,
            "stealth": StealthLevel.STEALTH,
            "paranoid": StealthLevel.PARANOID,
        }
        evasion_profile = EvasionProfile(stealth_level=stealth_map.get(stealth_level, StealthLevel.NORMAL))
        engine = EvasionEngine(evasion_profile)
        evasion_hdrs = engine.get_http_headers()

        # WAF fingerprinting
        profile.waf = await self.fingerprint_waf(session, url)

        # Technology fingerprinting from headers and body
        try:
            async with session.get(url, headers=evasion_hdrs,
                                   timeout=aiohttp.ClientTimeout(total=10)) as resp:
                headers = dict(resp.headers)
                body = await resp.text()
                profile.server = headers.get("Server", "")
                profile.interesting_headers = {
                    k: v for k, v in headers.items()
                    if k.lower() in ("x-powered-by", "x-aspnet-version", "x-generator",
                                     "x-drupal-cache", "x-frame-options", "content-security-policy",
                                     "x-xss-protection", "strict-transport-security")
                }

                # Framework detection
                powered_by = headers.get("X-Powered-By", "").lower()
                if "php" in powered_by:
                    profile.language = "php"
                elif "asp" in powered_by:
                    profile.language = "asp.net"
                elif "express" in powered_by:
                    profile.language = "node.js"

                # Body-based tech detection
                tech_patterns = [
                    (r"wp-content|wordpress", "WordPress"),
                    (r"drupal\.settings|Drupal", "Drupal"),
                    (r"joomla", "Joomla"),
                    (r"laravel|csrf-token.*laravel", "Laravel"),
                    (r"django|csrfmiddlewaretoken", "Django"),
                    (r"flask|werkzeug", "Flask"),
                    (r"spring|jsessionid", "Spring"),
                    (r"react|__NEXT_DATA__|_next/", "React/Next.js"),
                    (r"angular|ng-version", "Angular"),
                    (r"vue\.js|nuxt", "Vue.js"),
                    (r"graphql|__schema", "GraphQL"),
                    (r"swagger|openapi", "Swagger/OpenAPI"),
                ]
                for pattern, tech in tech_patterns:
                    if re.search(pattern, body, re.IGNORECASE):
                        profile.technologies.append(tech)

                # Auth detection
                if "authorization" in str(headers).lower() or "bearer" in body.lower():
                    profile.auth_type = "bearer"
                elif "set-cookie" in str(headers).lower():
                    profile.auth_type = "cookie"
                elif "www-authenticate" in str(headers).lower():
                    profile.auth_type = "basic"

                # API style
                if "graphql" in body.lower() or "graphql" in url.lower():
                    profile.api_style = "graphql"
                elif "wsdl" in body.lower() or "soap" in body.lower():
                    profile.api_style = "soap"
                elif "application/json" in headers.get("Content-Type", ""):
                    profile.api_style = "rest"

        except Exception as e:
            logger.debug(f"Profiling error for {url}: {e}")

        # Recommend attack strategies based on profile
        profile.recommended_attacks = self._recommend_attacks(profile)

        self.profiles[url] = profile
        logger.info(f"🎯 Target profiled: {url} — server={profile.server}, "
                     f"tech={profile.technologies}, waf={profile.waf.name if profile.waf else 'none'}")
        return profile

    def _recommend_attacks(self, profile: TargetProfile) -> list[str]:
        """Recommend attack strategies based on target intelligence."""
        attacks = []

        # Technology-specific recommendations
        for tech in profile.technologies:
            tech_lower = tech.lower()
            if "wordpress" in tech_lower:
                attacks.extend(["wpscan", "xmlrpc_bruteforce", "plugin_vulns", "user_enumeration"])
            elif "drupal" in tech_lower:
                attacks.extend(["drupalgeddon", "module_enum", "admin_bruteforce"])
            elif "django" in tech_lower:
                attacks.extend(["debug_mode_check", "ssti_jinja2", "admin_panel"])
            elif "flask" in tech_lower:
                attacks.extend(["ssti_jinja2", "debug_console", "pickle_deserialization"])
            elif "spring" in tech_lower:
                attacks.extend(["spring4shell", "actuator_exposure", "spel_injection"])
            elif "graphql" in tech_lower:
                attacks.extend(["introspection_query", "batch_query_dos", "field_suggestion"])
            elif "react" in tech_lower or "next" in tech_lower:
                attacks.extend(["prototype_pollution", "ssrf_via_proxy", "source_map_exposure"])

        # Server-specific
        if "nginx" in profile.server.lower():
            attacks.append("nginx_off_by_slash")
        elif "apache" in profile.server.lower():
            attacks.append("apache_mod_status")
        elif "iis" in profile.server.lower():
            attacks.extend(["iis_shortname", "web_config_exposure"])

        # Auth-specific
        if profile.auth_type == "bearer":
            attacks.extend(["jwt_none_alg", "jwt_weak_secret", "token_replay"])
        elif profile.auth_type == "cookie":
            attacks.extend(["session_fixation", "cookie_tampering"])

        # Missing security headers
        if "content-security-policy" not in {k.lower() for k in profile.interesting_headers}:
            attacks.append("xss_no_csp")
        if "strict-transport-security" not in {k.lower() for k in profile.interesting_headers}:
            attacks.append("ssl_stripping")

        # WAF bypass
        if profile.waf:
            attacks.append(f"waf_bypass_{profile.waf.name}")

        return list(set(attacks))

    def adapt_rate(self, host: str, response_time_ms: float, status: int) -> dict:
        """Adapt scanning rate based on target responses."""
        self._request_count[host] += 1

        if status == 429:
            self._blocked_count[host] += 1
            # Back off exponentially
            backoff = min(2 ** self._blocked_count[host], 60)
            return {"action": "backoff", "delay_seconds": backoff,
                    "reason": "Rate limit detected (HTTP 429)"}

        if status in (403, 406, 503):
            self._blocked_count[host] += 1
            if self._blocked_count[host] > 3:
                return {"action": "switch_evasion", "level": "stealth",
                        "reason": f"Multiple blocks detected ({self._blocked_count[host]})"}

        if response_time_ms > 10000:
            return {"action": "slow_down", "delay_seconds": 2,
                    "reason": "Target responding slowly"}

        return {"action": "continue", "delay_seconds": 0}
